const test = require('node:test');
const assert = require('node:assert/strict');

const controllerPath = require.resolve('../controllers/authController');
const userPath = require.resolve('../models/User');
const invitePath = require.resolve('../models/Invite');
const dbPath = require.resolve('../db');
const bcryptPath = require.resolve('bcryptjs');
const nodemailerPath = require.resolve('nodemailer');

function mockModule(modulePath, exports) {
  require.cache[modulePath] = { id: modulePath, filename: modulePath, loaded: true, exports };
}

function response() {
  return {
    statusCode: 200,
    body: null,
    status(code) { this.statusCode = code; return this; },
    json(body) { this.body = body; return this; },
  };
}

function loadController(user, captureMail) {
  for (const modulePath of [controllerPath, userPath, invitePath, dbPath, bcryptPath, nodemailerPath]) {
    delete require.cache[modulePath];
  }
  mockModule(userPath, { User: user, Community: {} });
  mockModule(invitePath, { Invite: {} });
  mockModule(dbPath, { pool: {} });
  mockModule(bcryptPath, { hash: async () => 'password-hash' });
  mockModule(nodemailerPath, {
    createTransport: () => ({ sendMail: captureMail }),
    getTestMessageUrl: () => null,
  });
  return require(controllerPath);
}

test('forgot-password ignores hostile Host headers and uses only configured origin', async () => {
  const previousOrigin = process.env.PUBLIC_APP_URL;
  process.env.PUBLIC_APP_URL = 'https://trusted.example.test/';
  let mail;
  let stored;
  const user = {
    findByEmail: async () => ({ id: 7, email: 'resident@example.test' }),
    setResetToken: async (email, token, expires) => {
      stored = { email, token, expires };
      return true;
    },
  };
  const { forgotPassword } = loadController(user, async options => { mail = options; return {}; });
  const res = response();

  try {
    await forgotPassword({
      body: { email: 'resident@example.test' },
      protocol: 'https',
      headers: { host: 'host-attacker.example', 'x-forwarded-host': 'forwarded-attacker.example' },
      get: () => 'host-attacker.example',
    }, res);
  } finally {
    process.env.PUBLIC_APP_URL = previousOrigin;
  }

  assert.equal(res.statusCode, 200);
  assert.match(mail.html, /https:\/\/trusted\.example\.test\/api\/auth\/reset-password\/[a-f0-9]{64}/);
  assert.doesNotMatch(mail.html, /host-attacker|forwarded-attacker/);
  assert.equal(stored.token.length, 64);
  assert.ok(stored.expires.getTime() > Date.now() + 55 * 60 * 1000);
});

test('a reset token generated by the normal flow still completes once', async () => {
  const previousOrigin = process.env.PUBLIC_APP_URL;
  process.env.PUBLIC_APP_URL = 'http://localhost.test';
  let storedToken;
  let updated;
  const user = {
    findByEmail: async () => ({ id: 8, email: 'resident@example.test' }),
    setResetToken: async (email, token) => { storedToken = token; return true; },
    findByResetToken: async token => token === storedToken ? { id: 8 } : null,
    updatePassword: async (id, passwordHash) => { updated = { id, passwordHash }; return true; },
  };
  const controller = loadController(user, async () => ({}));
  const forgotRes = response();
  const resetRes = response();

  try {
    await controller.forgotPassword({ body: { email: 'resident@example.test' } }, forgotRes);
    await controller.resetPassword({ params: { token: storedToken }, body: { password: 'Secure123!' } }, resetRes);
  } finally {
    process.env.PUBLIC_APP_URL = previousOrigin;
  }

  assert.equal(forgotRes.statusCode, 200);
  assert.equal(resetRes.statusCode, 200);
  assert.deepEqual(updated, { id: 8, passwordHash: 'password-hash' });
});
