const test = require('node:test');
const assert = require('node:assert/strict');

const controllerPath = require.resolve('../controllers/authController');
const userPath = require.resolve('../models/User');
const invitePath = require.resolve('../models/Invite');
const dbPath = require.resolve('../db');
const bcryptPath = require.resolve('bcryptjs');
const accountEmailPath = require.resolve('../services/accountEmail');
const crypto = require('node:crypto');
const jwt = require('jsonwebtoken');

function mockModule(modulePath, exports) {
  require.cache[modulePath] = { id: modulePath, filename: modulePath, loaded: true, exports };
}

function response() {
  return {
    statusCode: 200,
    body: null,
    status(code) { this.statusCode = code; return this; },
    json(body) { this.body = body; return this; },
  };
}

function flushImmediate() {
  return new Promise(resolve => setImmediate(resolve));
}

function loadController(user, sendPasswordResetEmail) {
  for (const modulePath of [controllerPath, userPath, invitePath, dbPath, bcryptPath, accountEmailPath]) {
    delete require.cache[modulePath];
  }
  mockModule(userPath, { User: user, Community: {} });
  mockModule(invitePath, { Invite: {} });
  mockModule(dbPath, { pool: {} });
  mockModule(bcryptPath, { hash: async () => 'password-hash', compare: async () => true });
  mockModule(accountEmailPath, { sendPasswordResetEmail });
  return require(controllerPath);
}

test('forgot-password ignores hostile Host headers and uses only configured origin', async () => {
  const previousOrigin = process.env.PUBLIC_APP_URL;
  process.env.PUBLIC_APP_URL = 'https://trusted.example.test/';
  let resetEmail;
  let stored;
  const user = {
    findByEmail: async () => ({ id: 7, email: 'resident@example.test' }),
    setResetToken: async (email, tokenHash, expires) => {
      stored = { email, tokenHash, expires };
      return { id: 7, email };
    },
  };
  const { forgotPassword } = loadController(user, async options => { resetEmail = options; return {}; });
  const res = response();

  try {
    await forgotPassword({
      body: { email: 'resident@example.test' },
      protocol: 'https',
      headers: { host: 'host-attacker.example', 'x-forwarded-host': 'forwarded-attacker.example' },
      get: () => 'host-attacker.example',
    }, res);
    await flushImmediate();
  } finally {
    process.env.PUBLIC_APP_URL = previousOrigin;
  }

  assert.equal(res.statusCode, 200);
  assert.match(resetEmail.resetUrl, /^https:\/\/trusted\.example\.test\/reset-password#token=[a-f0-9]{64}$/);
  assert.doesNotMatch(resetEmail.resetUrl, /api\/auth\/reset-password|host-attacker|forwarded-attacker/);
  const rawToken = resetEmail.resetUrl.match(/#token=([a-f0-9]{64})/)[1];
  assert.equal(stored.tokenHash.length, 64);
  assert.notEqual(stored.tokenHash, rawToken);
  assert.equal(stored.tokenHash, crypto.createHash('sha256').update(rawToken).digest('hex'));
  assert.ok(stored.expires.getTime() > Date.now() + 55 * 60 * 1000);
});

test('a reset token generated by the normal flow still completes once', async () => {
  const previousOrigin = process.env.PUBLIC_APP_URL;
  process.env.PUBLIC_APP_URL = 'http://localhost.test';
  let storedHash;
  let rawToken;
  let updated;
  let consumed = false;
  const user = {
    findByEmail: async () => ({ id: 8, email: 'resident@example.test' }),
    setResetToken: async (email, tokenHash) => {
      storedHash = tokenHash;
      return { id: 8, email };
    },
    consumeResetToken: async (tokenHash, passwordHash) => {
      if (consumed || tokenHash !== storedHash) return null;
      consumed = true;
      updated = { id: 8, passwordHash };
      return { id: 8, auth_version: 1 };
    },
  };
  const controller = loadController(user, async resetEmail => {
    rawToken = resetEmail.resetUrl.match(/#token=([a-f0-9]{64})/)?.[1];
    return {};
  });
  const forgotRes = response();
  const resetRes = response();
  const repeatedRes = response();

  try {
    await controller.forgotPassword({ body: { email: 'resident@example.test' } }, forgotRes);
    await flushImmediate();
    assert.equal(typeof rawToken, 'string', 'recovery email must contain a fragment token');
    await controller.resetPassword({ params: { token: rawToken }, body: { password: 'Secure123!' } }, resetRes);
    await controller.resetPassword({ params: { token: rawToken }, body: { password: 'Other123!' } }, repeatedRes);
  } finally {
    process.env.PUBLIC_APP_URL = previousOrigin;
  }

  assert.equal(forgotRes.statusCode, 200);
  assert.equal(resetRes.statusCode, 200);
  assert.equal(repeatedRes.statusCode, 400);
  assert.deepEqual(updated, { id: 8, passwordHash: 'password-hash' });
});

test('forgot-password is externally identical for unknown, delivered and failed-delivery accounts', async () => {
  const expected = { message: 'Si el email existe, recibirás un enlace de restablecimiento' };

  const unknownController = loadController({ setResetToken: async () => null }, async () => {
    throw new Error('mail should not be attempted');
  });
  const unknownRes = response();
  await unknownController.forgotPassword({ body: { email: 'unknown@example.test' } }, unknownRes);

  const deliveredController = loadController({
    setResetToken: async () => ({ id: 10, email: 'known@example.test' }),
  }, async () => ({}));
  const deliveredRes = response();
  await deliveredController.forgotPassword({ body: { email: 'known@example.test' } }, deliveredRes);
  await flushImmediate();

  const failedController = loadController({
    setResetToken: async () => ({ id: 10, email: 'known@example.test' }),
  }, async () => { throw new Error('SMTP unavailable'); });
  const failedRes = response();
  const originalError = console.error;
  let internalFailureLogged = false;
  console.error = (...args) => {
    internalFailureLogged = args.length === 1 && args[0] === 'Falló la entrega de recuperación de contraseña.';
  };
  try {
    await failedController.forgotPassword({ body: { email: 'known@example.test' } }, failedRes);
    await flushImmediate();
  } finally {
    console.error = originalError;
  }

  for (const res of [unknownRes, deliveredRes, failedRes]) {
    assert.equal(res.statusCode, 200);
    assert.deepEqual(res.body, expected);
  }
  assert.equal(internalFailureLogged, true);
});

test('forgot-password response does not wait for SMTP completion', async () => {
  let releaseDelivery;
  let deliveryStarted = false;
  const delivery = new Promise(resolve => { releaseDelivery = resolve; });
  const controller = loadController({
    setResetToken: async (email) => ({ id: 12, email }),
  }, async () => {
    deliveryStarted = true;
    await delivery;
    return {};
  });
  const res = response();

  await controller.forgotPassword({ body: { email: 'known@example.test' } }, res);
  assert.equal(res.statusCode, 200);
  await flushImmediate();
  assert.equal(deliveryStarted, true);
  releaseDelivery();
  await flushImmediate();
});

test('expired or already consumed reset token keeps the generic invalid-token contract', async () => {
  const controller = loadController({ consumeResetToken: async () => null }, async () => ({}));
  const res = response();

  await controller.resetPassword({
    params: { token: 'synthetic-expired-token' },
    body: { password: 'Secure123!' },
  }, res);

  assert.equal(res.statusCode, 400);
  assert.deepEqual(res.body, { error: 'Token inválido o expirado' });
});

test('reset database failure remains a server failure', async () => {
  const controller = loadController({
    consumeResetToken: async () => { throw new Error('database failure'); },
  }, async () => ({}));
  const res = response();
  const originalError = console.error;
  console.error = () => {};
  try {
    await controller.resetPassword({
      params: { token: 'synthetic-token' },
      body: { password: 'Secure123!' },
    }, res);
  } finally {
    console.error = originalError;
  }

  assert.equal(res.statusCode, 500);
});

test('login signs the current auth version without exposing it in the user response', async () => {
  const user = {
    findByEmail: async () => ({
      id: 20,
      email: 'resident@example.test',
      role: 'residente',
      password_hash: 'stored-hash',
      auth_version: 3,
    }),
    findById: async () => ({
      id: 20,
      email: 'resident@example.test',
      role: 'residente',
      community_id: 1,
    }),
  };
  const controller = loadController(user, async () => ({}));
  const res = response();

  await controller.login({
    body: { email: 'resident@example.test', password: 'Secure123!' },
  }, res);

  const decoded = jwt.verify(res.body.token, process.env.JWT_SECRET);
  assert.equal(decoded.auth_version, 3);
  assert.equal(Object.prototype.hasOwnProperty.call(res.body.user, 'auth_version'), false);
});
