ALTER TABLE announcements
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;

ALTER TABLE expenses
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;

ALTER TABLE tickets
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
