ALTER TABLE buildings ADD COLUMN IF NOT EXISTS building_type VARCHAR(30);
ALTER TABLE buildings ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;

ALTER TABLE floors ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;

ALTER TABLE units ADD COLUMN IF NOT EXISTS unit_type VARCHAR(30);
ALTER TABLE units ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE units ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_units_active ON units(is_active);
CREATE INDEX IF NOT EXISTS idx_units_type ON units(unit_type);
